# Setup
title: Jonie Learning
description: I'm putting together my portfolio.
url: https://joniekwon.github.io/
baseurl: /joniekwon
avatar: /img/avatar.JPG
paginate: 5
permalink: pretty
cover_image: /img/background.jpg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Jonie Kwon
  card: summary
logo: logo.png
social:
  name: Jonie Kwon
  links:
    #- https://twitter.com/joniekwon
    - https://github.com/joniekwon
google_site_verification: google-site-verification=IySA_uI0fFtRMqzY49zEyLwZpxaeCGKDEnzsQwrzCwo
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Jonie Kwon
  url: https://github.com/joniekwon
  email: kkkji1215@naver.com

markdown: kramdown
kramdown:
    extensions: ["tables"]
    highlighter: rouge
    syntax_highlighter_opts:
        block:
            line_numbers: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"